
GET http://api.openweathermap.org/data/2.5/air_pollution?lat={18.451726}&lon={-69.961452}&appid={f264a6f1f41af2ed5d7d17c8ecadffb8}

###

POST http://localhost:3000/aqi
Content-Type: application/json

{
    "aqi": "2.5",
    "comp": ""
}